apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: edu-canary
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary
  template:
    metadata:
      labels:
        app: canary
    spec:
      containers:
      - name: frontend
        image: ghcr.io/shclub/vue3:v2
        imagePullPolicy: Always
        env:
        - name: BACKEND_API_URL
          value: "backend" 
        ports:
        - containerPort: 80
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 25
      - pause: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
